const mode = color_modes[cb_obj.active];
const is_group = (mode === "Group");
const is_feature = (mode === "Feature");
const is_top = (mode === "Top feature");
for (const g of group_glyphs) g.visible = is_group;
top_other_glyph.visible = is_top;
top_named_glyph.visible = is_top;
gradient_glyph.visible = is_feature;
color_bar.visible = is_feature;
feature_picker.visible = is_feature;
top_n_slider.visible = is_top;
