[build-system]
requires = ["uv_build>=0.6.6"]
build-backend = "uv_build"

[project]
name = "glass-box-umap"
version = "0.0.0"
description = "This package augments UMAP by computing exact feature contributions to the UMAP embedding."
authors = [
  {name = "James Golden", email = "james.golden@arcadiascience.com"},
  {name = "Evan Kiefl", email = "kiefl.evan@gmail.com"},
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10,<4.0"
# TODO: We'll eventually want to increase dependency resolution radius
# TODO: We'll want to strictly prune these deps
dependencies = [
    "numpy>=1.26.4,<2",
    "plotly>=6.3.1,<7",
    "pandas>=2.2.3,<3",
    "adjusttext>=1.3.0,<2",
    "anndata>=0.11.4,<0.12",
    "arcadia-pycolor>=0.6.5,<0.7",
    "array-api-compat>=1.12.0,<2",
    "colorspacious>=1.1.2,<2",
    "crc32c>=2.7.1,<3",
    "donfig>=0.8.1,<0.9",
    "igraph>=0.11.9,<0.12",
    "kaleido>=0.2.1,<0.3",
    "legacy-api-wrap>=1.4.1,<2",
    "leidenalg>=0.10.2,<0.11",
    "lightning-utilities>=0.15.2,<0.16",
    "numcodecs>=0.13.1,<0.14",
    "scanpy>=1.11.4,<2",
    "session-info2>=0.2.3,<0.3",
    "texttable>=1.7.0,<2",
    "zarr>=2.18.3,<3",
    "dill>=0.4.0,<0.5",
    "einops>=0.8.1,<0.9",
]

# https://github.com/python-poetry/poetry/issues/6409#issuecomment-2203773939
#torchmetrics
#pytorch-lightning
#torch

[project.urls]
Homepage = "https://github.com/Arcadia-Science/glass-box-umap"
Repository = "https://github.com/Arcadia-Science/glass-box-umap"
Documentation = "https://github.com/Arcadia-Science/glass-box-umap/blob/main/README.md"

[dependency-groups]
dev = [
    "pre-commit==3.5.0",
    "pyright>=1.1.367,<2",
    "pytest==8.2.1",
    "ruff==0.4.4",
]
docs = [
    "sphinx==8.1.3",
    "sphinx-copybutton==0.5.2",
    "furo==2024.8.6",
    "myst-parser==4.0.1",
    "sphinx-autoapi==3.6.0",
    "sphinx-tabs==3.4.7",
    "nbsphinx==0.9.7",
    "sphinx-autobuild==2024.10.3",
    "sphinx-togglebutton==0.3.2",
    "astroid==3.3.11",
    # Jupyterlab and matplotlib are needed for notebook rendering.
    "jupyterlab==4.2.5",
    "matplotlib==3.9.2",
]

[tool.ruff]
# The directories to consider when resolving first- vs. third-party imports.
src = ["."]
line-length = 100
indent-width = 4
extend-include = ["*.ipynb"]

[tool.ruff.lint.per-file-ignores]
# Ignore star and unused imports.
"__init__.py" = ["F403", "F405"]

[tool.ruff.lint]
select = [
    "B",  # flake8-bugbear
    "E",  # pycodestyle error
    "F",  # pyflakes
    "I",  # isort
    "UP", # pyupgrade
    "W",  # pycodestyle warning
]
ignore = []
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
order-by-type = true
no-lines-before = ["future", "standard-library"]

[tool.pyright]
typeCheckingMode = "basic"
exclude = ["./.venv", "./dist"]

# Pyright reports a lot of unknown-member errors for some packages.
# If this is a problem, set this to `false`.
reportUnknownMemberType = true
